version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
  backend:
    build: .
    command: npm run dev
    ports:
      - '5555:5555'
    volumes:
      - '.:/usr/app'
    env_file: '.env.dev'
    depends_on:
      - db
    links:
      - db
networks:
  default:
    external:
      name: local
